language: node_js
node_js: 8
before_script:
  - npm install firebase-tools -g
  - cd functions && npm install
  - cd ..
  - npm install
  - gulp
branches:
  only:
    - live
script:
  - firebase deploy --token $FIREBASE_TOKEN